contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('', views.ContactView.as_view(), name='contact'),
    ]

multi_store/urls.py
from django.urls import path
from . import views

app_name = 'test'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('shop/', views.ShopCategoryView.as_view(), name='shop_category'),
    path('shop/category/<int:category_id>/', views.ShopGroupsView.as_view(), name='shop_groups'),
    path('products/<int:group_id>/', views.ShopProductsView.as_view(), name='shop_products'),
    path('product_detail/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('search/<str:name>/', views.SearchView.as_view(), name='search'),
]

shoping_cart/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'shoping_cart'

urlpatterns = [
    path('cart/', login_required(views.CartView.as_view()), name='cart'),
    path('checkout/', login_required(views.CheckOutView.as_view()), name='checkout'),
    path('cart/add/<int:product_id>', views.add_to_basket, name='add_to_cart'),
    path('cart/remove/<int:product_id>', views.del_from_basket, name='del_from_basket'),
    path('cart/delete/<int:basket_id>', views.remove_basket, name='remove_basket'),
    path('likes/', login_required(views.LikesView.as_view()), name='likes'),
    path('likes/add/<int:product_id>', views.add_to_likes, name='add_to_likes'),
    path('likes/delete/<int:product_id>', views.del_from_likes, name='del_from_likes'),
    path('checkout/success/', login_required(views.SuccessView.as_view()), name='success_view'),
    path('checkout/cancel/', login_required(views.CancelView.as_view()), name='cancel_view'),
    path('checkouts/', login_required(views.CheckoutsListView.as_view()), name='checkouts_list'),
    path('checkouts/order_detail/<int:pk>', login_required(views.OrderDetailView.as_view()), name='order_detail'),
    path('checkout/purchase/', views.stripe_webhook),
    ]

test_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('multi_store.urls', namespace='test')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('user/', include('users.urls', namespace='users')),
    path('shopingcart/', include('shoping_cart.urls', namespace='shoping_cart')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('registration/', views.RegistrationView.as_view(), name='registration'),
    path('logout/', views.UserLogOutView.as_view(), name='logout'),
    ]

shoping_cart/models.py
from datetime import datetime

from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator

from multi_store.models import Products, UserShoppingCart


# Create your models here.


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=datetime.now)


class CartItem(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=1, validators=[MinValueValidator(1)])
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)

    def increment_item(self):
        self.quantity += 1
        return self

    def decrement_item(self):
        self.quantity -= 1
        return self


class CheckoutOrder(models.Model):
    CREATED = 0
    PAID = 1
    COMPLETED = 2
    ON_WAY = 3
    DELIVERED = 4

    UKRAINE = 0
    POLAND = 1

    STATUSES = (
        (CREATED, 'CREATED'),
        (PAID, 'PAID'),
        (COMPLETED, 'COMPLETED'),
        (DELIVERED, 'DELIVERED'),
    )

    COUNTRY = (
        (UKRAINE, 'UKRAINE'),
        (POLAND, 'POLAND'),
    )

    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    email = models.EmailField(max_length=64)
    mobile_no = models.CharField(max_length=13)
    address = models.CharField(max_length=256)
    country = models.SmallIntegerField(default=UKRAINE, choices=COUNTRY)
    city = models.CharField(max_length=64)
    state = models.CharField(max_length=64)
    zip_code = models.PositiveSmallIntegerField()

    status = models.SmallIntegerField(default=CREATED, choices=STATUSES)
    initiator = models.ForeignKey(User, on_delete=models.CASCADE)

    created = models.DateTimeField(auto_now_add=True)
    basket_history = models.JSONField(default=dict)

    def status_paid(self, mark):
        carts = UserShoppingCart.objects.filter(user=self.initiator)
        self.basket_history = {
            'cart': [cart.checkout_json() for cart in carts],
            'total_sum': round(carts.total_sum()),
            'total_sum_tax': round(carts.total_sum_tax()),
        }
        self.save()
        self.status = self.PAID
        carts.delete()


class Likes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    added = models.DateTimeField(auto_now_add=True)

shoping_cart/forms.py
from django import forms
from multi_store.models import UserShoppingCart
from .models import CheckoutOrder


class ShoppingCartForm(forms.ModelForm):
    quantity = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control form-control-sm bg-secondary border-0 text-center', 'value': 'cart.quantity'
    }))

    class Meta:
        model = UserShoppingCart
        fields = ['quantity']


class CheckOutForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'type': 'text', 'placeholder': 'Your name'
    }))

    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'type': 'text', 'placeholder': 'Your last name'
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control', 'type': 'text', 'placeholder': 'example@email.com'
    }))

    mobile_no = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'type': 'text', 'placeholder': '+380 96 22 55 888'
    }))

    address = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'type': 'text', 'placeholder': '123 Street'
    }))

    country = forms.ChoiceField(choices=CheckoutOrder.COUNTRY, widget=forms.Select(attrs={
        'class': 'form-control', 'type': 'text'
    }))

    city = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'type': 'text', 'placeholder': 'Kyiv'
    }))

    state = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'type': 'text', 'placeholder': 'Kyiv'
    }))

    zip_code = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'type': 'text', 'placeholder': '80056'
    }))

    class Meta:
        model = CheckoutOrder
        fields = [
            'first_name',
            'last_name',
            'email',
            'mobile_no',
            'address',
            'country',
            'city',
            'state',
            'zip_code',
        ]

shoping_cart/views.py
from http import HTTPStatus

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse_lazy, reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView, DeleteView, CreateView, ListView
from common.views import EmailNewsMixin

from .models import Cart, CartItem, Likes, CheckoutOrder
from multi_store.models import UserShoppingCart
from .forms import ShoppingCartForm, CheckOutForm
from django.conf import settings
from common.views import CategoriesListMixin

from multi_store.models import ProductsCategories, ProductsSubGroup, UserShoppingCart

import stripe

# Create your views here.
stripe.api_key = settings.STRIPE_SECRET_KEY
YOUR_DOMAIN = settings.DOMAIN_NAME
endpoint_secret = settings.STRIPE_ENDPOINT_SECRET


class CartView(EmailNewsMixin, CategoriesListMixin, TemplateView):
    template_name = 'shoping_cart/cart.html'
    products_categories = ProductsCategories.objects.all()
    products_groups = ProductsSubGroup.objects.all()

    # form_class = ShoppingCartForm

    def get_context_data(self, **kwargs):
        data = super(CartView, self).get_context_data(**kwargs)
        data['shopping_cart'] = UserShoppingCart.objects.filter(user=self.request.user)
        return data


@login_required
def add_to_basket(request, product_id):
    baskets = UserShoppingCart.objects.filter(user=request.user, product_id=product_id)

    if not baskets.exists():
        UserShoppingCart.objects.create(user=request.user, product_id=product_id, quantity=1)
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def del_from_basket(request, product_id):
    baskets = UserShoppingCart.objects.filter(user=request.user, product_id=product_id)

    if baskets.exists():
        basket = baskets.first()
        if basket.quantity > 0:
            basket.quantity -= 1
            basket.save()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def remove_basket(request, basket_id):
    basket = UserShoppingCart.objects.filter(id=basket_id)
    basket.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


class DeleteFromCartView(DeleteView):
    model = Cart
    success_url = reverse_lazy('shoping_cart:cart')


class CheckOutView(EmailNewsMixin, CategoriesListMixin, CreateView):
    template_name = 'shoping_cart/checkout.html'
    products_categories = ProductsCategories.objects.all()
    products_groups = ProductsSubGroup.objects.all()
    form_class = CheckOutForm
    success_url = reverse_lazy('shoping_cart:checkout')

    def post(self, request, *args, **kwargs):
        super().post(request, *args, **kwargs)
        try:
            checkout_session = stripe.checkout.Session.create(
                line_items=[
                    {
                        'price': 'price_1Mj2IOFJ5I6YSCca27Dwf1lS',
                        'quantity': 1,
                    },
                ],
                metadata={'checkout_id': self.object.id},
                mode='payment',
                success_url='{}{}'.format(YOUR_DOMAIN, reverse('shoping_cart:success_view')),
                cancel_url='{}{}'.format(YOUR_DOMAIN, reverse('shoping_cart:cancel_view')),
            )
        except Exception as e:
            return repr(e)

        return HttpResponseRedirect(checkout_session.url, status=HTTPStatus.SEE_OTHER)

    def form_valid(self, form):
        form.instance.initiator = self.request.user
        return super().form_valid(form)


@csrf_exempt
def stripe_webhook(request):
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, endpoint_secret
        )
    except ValueError as e:
        # Invalid payload
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError as e:
        # Invalid signature
        return HttpResponse(status=400)

    # Handle the checkout.session.completed event
    if event['type'] == 'checkout.session.completed':
        session = event['data']['object']
        # Fulfill the purchase...
        fulfill_order(session)

    # Passed signature verification
    return HttpResponse(status=200)


def fulfill_order(session):
    order = CheckoutOrder.objects.get(id=session['metadata']['checkout_id'])
    order.status_paid(mark=True)


class LikesView(TemplateView):
    template_name = 'shoping_cart/likes.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['likes'] = Likes.objects.filter(user=self.request.user)
        return data


@login_required
def add_to_likes(request, product_id):
    likes = Likes.objects.filter(user=request.user, product_id=product_id)

    if not likes.exists():
        Likes.objects.create(user=request.user, product_id=product_id)

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def del_from_likes(request, product_id):
    like = Likes.objects.filter(user=request.user, product_id=product_id)
    like.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


class SuccessView(TemplateView):
    template_name = 'shoping_cart/success.html'


class CancelView(TemplateView):
    template_name = 'shoping_cart/cart.html'


class CheckoutsListView(ListView):
    template_name = 'shoping_cart/checkouts_history.html'
    model = CheckoutOrder

    def get_queryset(self):
        data = super().get_queryset()
        return data.filter(initiator=self.request.user).order_by('-id')


class OrderDetailView(DeleteView):
    template_name = 'shoping_cart/order_detail.html'
    model = CheckoutOrder

shoping_cart/templates/shoping_cart/cancel.html
{% extends 'multi_store/base.html' %}
{% load static %}

<body>
{% block content %}
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8">
                <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">Successful payment</span>
                </h2>
                <div class="row px-xl-5">
                    <p>Your payment failed! You should contact us for more details and perhaps try again later.</p>
                </div>

                <div class="row px-xl-5">
                    <p>Feel free to contact us and share your thoughts or tips on how to improve our service!</p>
                </div>

                <div class="row px-xl-5">
                    <p>If you have any troubles with your equipment feel free to contact with our technical support via
                        phone number +3 123 45 67 890 or via email support@mail.com</p>
                </div>
            </div>
        </div>
    </div>
    <div class="pt-2">
        <a href="{% url 'contact:contact' %}">
            <button class="btn btn-block btn-primary font-weight-bold my-3 py-3">Contact</button>
        </a>
    </div>
{% endblock %}
</body>

shoping_cart/templates/shoping_cart/cart.html
{% extends 'multi_store/base.html' %}
{% load static %}

<body>
{% block content %}
    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="{% url 'test:index' %}">Home</a>
                    <a class="breadcrumb-item text-dark" href="{% url 'test:shop_category' %}">Shop</a>
                    <span class="breadcrumb-item active">Shopping Cart</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- Cart Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-light table-borderless table-hover text-center mb-0">
                    <thead class="thead-dark">
                    <tr>
                        <th>Products</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Total</th>
                        <th>Remove</th>
                    </tr>
                    </thead>
                    <tbody class="align-middle">
                    {% for cart in shopping_cart %}
                        <tr>
                            <td class="align-middle"><img src="{{ cart.product.image.url }}" alt=""
                                                          style="width: 50px;">
                                <a href="{% url 'test:product_detail' cart.product.id %}"
                                   class="text-dark">{{ cart.product.name }}</a>
                            </td>
                            <td class="align-middle">${{ cart.product.price }}</td>
                            <td class="align-middle">
                                <div class="input-group quantity mx-auto" style="width: 100px;">
                                    <div class="input-group-btn">
                                        <a href="{% url 'shoping_cart:del_from_basket' cart.product.id %}"
                                           class="text-black-50">
                                            <button class="btn btn-sm btn-primary btn-minus">
                                                <i class="fa fa-minus"></i>
                                            </button>
                                        </a>
                                    </div>
                                    <input type="text"
                                           class="form-control form-control-sm bg-secondary border-0 text-center"
                                           value="{{ cart.quantity }}">
                                    <div class="input-group-btn">
                                        <a href="{% url 'shoping_cart:add_to_cart' cart.product.id %}"
                                           class="text-black-50">
                                            <button class="btn btn-sm btn-primary btn-plus">
                                                <i class="fa fa-plus"></i>
                                            </button>
                                        </a>
                                    </div>
                                </div>
                            </td>
                            <td class="align-middle">${{ cart.sum }}</td>

                            <td class="align-middle">
                                <a href="{% url 'shoping_cart:remove_basket' cart.id %}">
                                    <button class="btn btn-sm btn-danger" type="button">
                                        <i class="fa fa-times"></i>
                                    </button>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
{#                <form class="mb-30" action="">#}
{#                    <div class="input-group">#}
{#                        <input type="text" class="form-control border-0 p-4" placeholder="Coupon Code">#}
{#                        <div class="input-group-append">#}
{#                            <button class="btn btn-primary">Apply Coupon</button>#}
{#                        </div>#}
{#                    </div>#}
{#                </form>#}
                {% if shopping_cart %}
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Cart Summary</span>
                </h5>
                <div class="bg-light p-30 mb-5">
                    <div class="border-bottom pb-2">
                        <div class="d-flex justify-content-between mb-3">
                            <h6>Subtotal</h6>
                            <h6>${{ shopping_cart.total_sum }}</h6>
                        </div>
                        <div class="d-flex justify-content-between">
                            <h6 class="font-weight-medium">Shipping</h6>
                            <h6 class="font-weight-medium">$10</h6>
                        </div>
                    </div>
                    <div class="pt-2">
                        <div class="d-flex justify-content-between mt-2">
                            <h5>Total</h5>
                            <h5>${{ shopping_cart.total_sum_tax }}</h5>
                        </div>
                        <a href="{% url 'shoping_cart:checkout' %}">
                            <button class="btn btn-block btn-primary font-weight-bold my-3 py-3">Proceed To Checkout
                            </button>
                        </a>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
    <!-- Cart End -->



    </body>
{% endblock %}

shoping_cart/templates/shoping_cart/cart_check_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>
</body>
</html>

shoping_cart/templates/shoping_cart/checkouts_history.html
{% extends 'multi_store/base.html' %}
{% load static %}


{% block content %}
    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="{% url 'test:index' %}">Home</a>
                    <span class="breadcrumb-item active">Checkouts History</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- Checkouts Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-light table-borderless table-hover text-center mb-0">
                    <thead class="thead-dark">
                    <tr>
                        <th>Checkout ID</th>
                        <th>Status</th>
                        <th>Date</th>
                        <th>Total Sum</th>
                        <th>Detail</th>
                    </tr>
                    </thead>
                    <tbody class="align-middle">
                    {% for cart in object_list %}
                        <tr>
                            <td class="align-middle">{{ cart.id }}</td>
                            <td class="align-middle">{{ cart.get_status_display }}</td>
                            <td class="align-middle">{{ cart.created }}</td>
                            <td class="align-middle">${{ cart.basket_history.total_sum }}</td>

                            <td class="align-middle">
                                <a href="{% url 'shoping_cart:order_detail' cart.id %}">
                                    <button class="btn btn-sm btn-info" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- Checkouts End -->

{% endblock %}

shoping_cart/templates/shoping_cart/likes.html
{% extends 'multi_store/base.html' %}
{% load static %}

<body>
{% block content %}
    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="{% url 'test:index' %}">Home</a>
                    <a class="breadcrumb-item text-dark" href="{% url 'test:shop_category' %}">Shop</a>
                    <span class="breadcrumb-item active">Likes</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- Cart Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-light table-borderless table-hover text-center mb-0">
                    <thead class="thead-dark">
                        <tr>
                            <th>Products</th>
                            <th>Price</th>
                            <th>Add to cart</th>
                            <th>Remove</th>
                        </tr>
                    </thead>
                    <tbody class="align-middle">
                    {% for like in likes %}
                        <tr>
                            <td class="align-middle"><img src="{{ like.product.image.url }}" alt="" style="width: 50px;">
                                <a href="{% url 'test:product_detail' like.product.id %}" class="text-dark">{{ like.product.name }}</a>
                            </td>
                            <td class="align-middle">${{ like.product.price }}</td>
                            <td class="align-middle">
                                <a href="{% url 'shoping_cart:add_to_cart' like.product.id %}">
                                    <button class="btn btn-sm btn-warning" type="button">
                                        <i class="fa fa-shopping-cart"></i>
                                    </button>
                                </a>
                            </td>
                            <td class="align-middle">
                                <a href="{% url 'shoping_cart:del_from_likes' like.product.id %}">
                                    <button class="btn btn-sm btn-danger" type="button">
                                        <i class="fa fa-times"></i>
                                    </button>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

        </div>
    </div>
    <!-- Cart End -->



</body>
{% endblock %}

shoping_cart/templates/shoping_cart/order_detail.html
{% extends 'multi_store/base.html' %}
{% load humanize %}
{% load static %}

<body>
{% block content %}
    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="{% url 'test:index' %}">Home</a>
                    <a class="breadcrumb-item text-dark" href="{% url 'shoping_cart:checkouts_list' %}">Checkouts History</a>
                    <span class="breadcrumb-item active">Checkout Detail</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- Cart Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-light table-borderless table-hover text-center mb-0">
                    <thead class="thead-dark">
                        <tr>
                            <th>Products</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody class="align-middle">
                    {% for item in object.basket_history.cart %}
                        <tr>
                            <td class="align-middle"><a href="{% url 'test:product_detail' item.product_id %}" class="text-dark">{{ item.product }}</a></td>
                            <td class="align-middle">$ {{ item.price|intcomma }}</td>
                            <td class="align-middle">{{ item.quantity }}</td>
                            <td class="align-middle">$ {{ item.sum|intcomma }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Cart Summary</span></h5>
                <div class="bg-light p-30 mb-5">
                    <div class="pt-2">
                        <div class="d-flex justify-content-between mt-2">
                            <h5>Total</h5>
                            <h5>${{ object.basket_history.total_sum }}</h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Cart End -->



</body>
{% endblock %}

shoping_cart/templates/shoping_cart/success.html
{% extends 'multi_store/base.html' %}
{% load static %}

<body>
{% block content %}
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8">
                <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">Successful payment</span>
                </h2>
                <div class="row px-xl-5">
                    <p>Your payment was successful! We will contact you to clarify the details.</p>
                </div>

                <div class="row px-xl-5">
                    <p>Feel free to contact us and share your thoughts or tips on how to improve our service!</p>
                </div>

                <div class="row px-xl-5">
                    <p>If you have any troubles with your equipment feel free to contact with our technical support via
                        phone number +3 123 45 67 890 or via email support@mail.com</p>
                </div>
            </div>
        </div>
    </div>
    <div class="pt-2">
        <a href="{% url 'contact:contact' %}">
            <button class="btn btn-block btn-primary font-weight-bold my-3 py-3">Contact</button>
        </a>
    </div>
{% endblock %}
</body>