test_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('multi_store.urls', namespace='test')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('user/', include('users.urls', namespace='users')),
    path('shopingcart/', include('shoping_cart.urls', namespace='shoping_cart')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('registration/', views.RegistrationView.as_view(), name='registration'),
    path('logout/', views.UserLogOutView.as_view(), name='logout'),
    ]

users/models.py
from django.db import models


# Create your models here.

class EmailNews(models.Model):
    email = models.EmailField()
    status = models.BooleanField(default=True)

users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django import forms

from .models import EmailNews


class NewUserForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'input', 'placeholder': 'Enter your first name'}))

    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'input', 'placeholder': 'Enter your last name'}))

    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'input', 'placeholder': 'Enter your username'}))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'input', 'placeholder': 'Enter your email'}))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'input', 'placeholder': 'Enter your password'}))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'input', 'placeholder': 'Confirm your password'}))

    class Meta:
        model = User
        fields = ("first_name", "last_name", "username", "email", "password1", "password2")


class UserLogInForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        "class": "input", "placeholder": "Enter your username"
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        "class": "input", "placeholder": "Password"
    }))

    class Meta:
        model = User
        fields = ('username', 'password')


class EmailNewsForm(forms.Form):
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control', 'placeholder': 'Enter your email'}))

    class Meta:
        model = EmailNews
        fields = ['email']

users/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .forms import *
from django.contrib.auth.models import User


# Create your views here.

class UserLoginView(LoginView):
    template_name = 'users/login_form.html'
    authentication_form = UserLogInForm


class RegistrationView(CreateView):
    model = User
    template_name = 'users/register_form.html'
    form_class = NewUserForm
    success_url = reverse_lazy('users:login')


class UserLogOutView(LogoutView):
    pass

users/templates/users/login_form.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="{% static 'css/loger_form.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>
<body>
    <div class="form-container">
        <p>Login</p>
    <form class="form" method="post" action="{% url 'users:login' %}">
        {% csrf_token %}

        <label for="{{ form.username.id_for_label }}">Username</label>
        {{ form.username }}

        <label for="{{ form.password.id_for_label }}">Password</label>
        {{ form.password }}

        <button type="submit">Submit</button>

    </form>
        <br>
        <a href="{% url 'users:registration' %}">Create Account</a>
    </div>
</body>
</html>

users/templates/users/register_form.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="{% static 'css/reger_form.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>
<body>
    <div class="form-container">
        <p>Registration</p>
    <form class="form" method="post" action="{% url 'users:registration' %}">
        {% csrf_token %}
        <label for="{{ form.first_name.id_for_label }}">First Name</label>
        {{ form.first_name }}

        <label for="{{ form.flast_name.id_for_label }}">Last Name</label>
        {{ form.last_name }}


        <label for="{{ form.username.id_for_label }}">Username</label>
        {{ form.username }}

        <label for="{{ form.email.id_for_label }}">Email</label>
        {{ form.email }}

        <label for="{{ form.password1.id_for_label }}">Password</label>
        {{ form.password1 }}

        <label for="{{ form.password2.id_for_label }}">Confirm Password</label>
        {{ form.password2 }}

        <button type="submit">Submit</button>
    </form>
    </div>
</body>
</html>