multi_store/urls.py
from django.urls import path
from . import views

app_name = 'test'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('shop/', views.ShopCategoryView.as_view(), name='shop_category'),
    path('shop/category/<int:category_id>/', views.ShopGroupsView.as_view(), name='shop_groups'),
    path('products/<int:group_id>/', views.ShopProductsView.as_view(), name='shop_products'),
    path('product_detail/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('search/<str:name>/', views.SearchView.as_view(), name='search'),
]

shoping_cart/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'shoping_cart'

urlpatterns = [
    path('cart/', login_required(views.CartView.as_view()), name='cart'),
    path('checkout/', login_required(views.CheckOutView.as_view()), name='checkout'),
    path('cart/add/<int:product_id>', views.add_to_basket, name='add_to_cart'),
    path('cart/remove/<int:product_id>', views.del_from_basket, name='del_from_basket'),
    path('cart/delete/<int:basket_id>', views.remove_basket, name='remove_basket'),
    path('likes/', login_required(views.LikesView.as_view()), name='likes'),
    path('likes/add/<int:product_id>', views.add_to_likes, name='add_to_likes'),
    path('likes/delete/<int:product_id>', views.del_from_likes, name='del_from_likes'),
    path('checkout/success/', login_required(views.SuccessView.as_view()), name='success_view'),
    path('checkout/cancel/', login_required(views.CancelView.as_view()), name='cancel_view'),
    path('checkouts/', login_required(views.CheckoutsListView.as_view()), name='checkouts_list'),
    path('checkouts/order_detail/<int:pk>', login_required(views.OrderDetailView.as_view()), name='order_detail'),
    path('checkout/purchase/', views.stripe_webhook),
    ]

test_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('multi_store.urls', namespace='test')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('user/', include('users.urls', namespace='users')),
    path('shopingcart/', include('shoping_cart.urls', namespace='shoping_cart')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('registration/', views.RegistrationView.as_view(), name='registration'),
    path('logout/', views.UserLogOutView.as_view(), name='logout'),
    ]

multi_store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

import stripe

# Create your models here.
stripe.api_key = settings.STRIPE_SECRET_KEY


class ProductsCategories(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return f'{self.name}'


class ProductsSubGroup(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    product_category = models.ForeignKey(ProductsCategories, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}'


class ResolutionAttrValue(models.Model):
    name = models.CharField(max_length=64)
    value = models.CharField(max_length=64)

    def __str__(self):
        return f'{self.value} MP'


class LensAttrValue(models.Model):
    name = models.CharField(max_length=64)
    value = models.CharField(max_length=64)

    def __str__(self):
        return f'{self.value} mm'


class CaseAttrValue(models.Model):
    name = models.CharField(max_length=64)
    value = models.CharField(max_length=64)

    def __str__(self):
        return f'{self.value}'


class IRAttrValue(models.Model):
    name = models.CharField(max_length=64)
    value = models.CharField(max_length=64)

    def __str__(self):
        return f'{self.value} m'


class IPProductAttr(models.Model):
    name = models.CharField(max_length=64)
    product_group = models.ForeignKey(ProductsSubGroup, on_delete=models.CASCADE)
    resolution = models.ForeignKey(ResolutionAttrValue, on_delete=models.CASCADE, related_name='resolution')
    lens = models.ForeignKey(LensAttrValue, on_delete=models.CASCADE, related_name='lens')
    case = models.ForeignKey(CaseAttrValue, on_delete=models.CASCADE, related_name='case')
    ir = models.ForeignKey(IRAttrValue, on_delete=models.CASCADE, related_name='ir')

    def __str__(self):
        return f'{self.name}'


class Products(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    information = models.TextField()
    image = models.FileField(upload_to='products_images')
    price = models.FloatField()
    in_stock = models.PositiveIntegerField(default=0)
    product_group = models.ForeignKey(ProductsSubGroup, on_delete=models.CASCADE)
    attribute = models.ForeignKey(IPProductAttr, on_delete=models.CASCADE)

    stripe_id = models.CharField(max_length=64, blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    def create_stripe_id(self):
        stripe_product = stripe.Product.create(
            name=self.name,
            default_price_data={
                'unit_amount': round(self.price * 100),
                'currency': 'usd',
            },
            expand=['default_price']
        )
        self.stripe_id = stripe_product['default_price']['id']

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.create_stripe_id()
        super().save(force_insert=False, force_update=False, using=None, update_fields=None)


# class TypicalProductAttr(models.Model):
#     sub_group_id = models.ForeignKey(ProductsSubGroup, on_delete=models.CASCADE)
#     name = models.CharField(max_length=200, default=None)
#
#     def __str__(self):
#         return f'{self.name}'
#
#
# class AttrValue(models.Model):
#     typical_pr_attr_id = models.ForeignKey(TypicalProductAttr, on_delete=models.CASCADE)
#     value = models.CharField(max_length=500)
#
#     def __str__(self):
#         return f'{self.value}'
#
#
# class ProductAttribute(models.Model):
#     sub_group_id = models.ForeignKey(ProductsSubGroup, on_delete=models.CASCADE)
#     product_id = models.ForeignKey(Products, on_delete=models.CASCADE)
#     attr_value = models.ForeignKey(AttrValue, on_delete=models.CASCADE)
#
#     def __str__(self):
#         return f'{self.product_id} - {self.attr_value}'


class BasketQuerySet(models.QuerySet):
    def total_sum(self):
        return sum(basket.sum() for basket in self)

    def total_sum_tax(self):
        return sum(basket.sum() for basket in self) + 10

    def total_quantity(self):
        return sum(basket.quantity for basket in self)


class UserShoppingCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    objects = BasketQuerySet.as_manager()

    def sum(self):
        return self.product.price * self.quantity

    def increment_quantity(self):
        self.quantity += 1

    def checkout_json(self):
        data = {
            'product_id': self.product.id,
            'product': self.product.name,
            'quantity': self.quantity,
            'price': round(self.product.price),
            'sum': round(self.sum())
        }
        return data

multi_store/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView, DetailView, ListView, FormView
from .filters import IPProductFilter
from .models import *
from common.views import CategoriesListMixin, EmailNewsMixin


# Create your views here.


class IndexView(EmailNewsMixin, CategoriesListMixin, TemplateView):
    template_name = 'multi_store/index.html'
    products_categories = ProductsCategories.objects.all()
    products_groups = ProductsSubGroup.objects.all()

    def get_context_data(self, **kwargs):
        data = super(IndexView, self).get_context_data(**kwargs)
        data['products'] = Products.objects.all().order_by('-id')[:4]
        return data

    def get(self, request, *args, **kwargs):
        data = super().get(request, *args, **kwargs)
        search = self.request.GET.get('search')
        if search:
            url = reverse('test:search', args=(search,))
            return HttpResponseRedirect(url)
        return data


class ShopCategoryView(EmailNewsMixin, CategoriesListMixin, ListView):
    template_name = 'multi_store/shop_categories.html'
    queryset = ProductsCategories.objects.all()
    products_categories = ProductsCategories.objects.all()
    products_groups = ProductsSubGroup.objects.all()


class ShopGroupsView(EmailNewsMixin, CategoriesListMixin, ListView):
    template_name = 'multi_store/shop_groups.html'
    model = ProductsSubGroup
    products_categories = ProductsCategories.objects.all()
    products_groups = ProductsSubGroup.objects.all()

    def get_queryset(self):
        data = super(ShopGroupsView, self).get_queryset()
        category_id = self.kwargs.get('category_id')
        return data.filter(product_category_id=category_id)


class ShopProductsView(EmailNewsMixin, CategoriesListMixin, ListView):
    template_name = 'multi_store/shop.html'
    model = Products
    products_categories = ProductsCategories.objects.all()
    products_groups = ProductsSubGroup.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        data = super().get_context_data(object_list=None, **kwargs)
        queryset = self.get_queryset()
        filters = IPProductFilter(self.request.GET, queryset)
        a = self.request
        b = self.kwargs
        # product_attribute = TypicalProductAttr.objects.filter(sub_group_id=self.kwargs['group_id'])
        # attr_value = [AttrValue.objects.filter(typical_pr_attr_id=tpa) for tpa in product_attribute]

        # data['product_attribute'] = product_attribute
        # data['attr_value'] = attr_value
        data['filters'] = filters
        data['groups'] = self.kwargs['group_id']
        return data

    def get_queryset(self):
        data = super(ShopProductsView, self).get_queryset()
        group_id = self.kwargs.get('group_id')
        data = data.filter(product_group_id=group_id)
        filters = IPProductFilter(self.request.GET, queryset=data)
        return filters.qs


class ProductDetailView(EmailNewsMixin, CategoriesListMixin, DetailView):
    model = Products
    template_name = 'multi_store/product_detail.html'
    products_categories = ProductsCategories.objects.all()
    products_groups = ProductsSubGroup.objects.all()


class SearchView(CategoriesListMixin, ListView):
    template_name = 'multi_store/search.html'
    model = Products
    products_categories = ProductsCategories.objects.all()
    products_groups = ProductsSubGroup.objects.all()

    def get_queryset(self):
        data = super().get_queryset()
        name = self.kwargs.get('name')
        return data.filter(name__contains=name)

multi_store/templates/multi_store/search.html
{% extends 'multi_store/base.html' %}
{% load static %}

<body>
{% block content %}
    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="{% url 'test:index' %}">Home</a>
                    <span class="breadcrumb-item active">Search Results</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- Products Start -->
    <div class="container-fluid pt-5 pb-3">
        <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">Search Results</span></h2>
        <div class="row px-xl-5">

            {% for product in object_list %}
                <div class="col-lg-3 col-md-4 col-sm-6 pb-1">
                <div class="product-item bg-light mb-4">
                    <div class="product-img position-relative overflow-hidden">
                        <img class="img-fluid w-100" src="{{ product.image.url }}" alt="">
                        <div class="product-action">
                            <a class="btn btn-outline-dark btn-square" href="{% url 'shoping_cart:add_to_cart' product.id %}"><i class="fa fa-shopping-cart"></i></a>
                            <a class="btn btn-outline-dark btn-square" href="{% url 'shoping_cart:add_to_likes' product.id %}"><i class="far fa-heart"></i></a>
{#                            <a class="btn btn-outline-dark btn-square" href=""><i class="fa fa-sync-alt"></i></a>#}
                            <a class="btn btn-outline-dark btn-square" href="{% url 'test:product_detail' product.id %}"><i class="fa fa-search"></i></a>
                        </div>
                    </div>
                    <div class="text-center py-4">
                        <a class="h6 text-decoration-none text-truncate" href="{% url 'test:product_detail' pk=product.id %}">{{ product.name }}</a>
                        <div class="d-flex align-items-center justify-content-center mt-2">
                            <h5>${{ product.price }}</h5><h6 class="text-muted ml-2"><del>${{ product.price }}</del></h6>
                        </div>
                        <div class="d-flex align-items-center justify-content-center mb-1">
                            <small class="fa fa-star text-primary mr-1"></small>
                            <small class="fa fa-star text-primary mr-1"></small>
                            <small class="fa fa-star text-primary mr-1"></small>
                            <small class="fa fa-star text-primary mr-1"></small>
                            <small class="fa fa-star text-primary mr-1"></small>
                            <small>(99)</small>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
    <!-- Products End -->



</body>
{% endblock %}

multi_store/templates/multi_store/shop.html
{% extends 'multi_store/base.html' %}
{% load static %}


{% block content %}
    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="{% url 'test:index' %}">Home</a>
                    <a class="breadcrumb-item text-dark" href="{% url 'test:shop_category' %}">Shop Categories</a>
                    <a class="breadcrumb-item text-dark"
                       href="{% url 'test:shop_groups' object_list.0.product_group.product_category.id %}">Shop
                        Groups</a>
                    <span class="breadcrumb-item active">Shop List</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- Shop Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <!-- Shop Sidebar Start -->
            <div class="col-lg-3 col-md-4">
                <form action=".">
                    {{ filters.form.as_p }}

                    {#                    {% for attr in product_attribute %}#}
                    {#                        <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">{{ attr.name }}</span></h5>#}
                    {#                        <div class="bg-light p-4 mb-30">#}
                    {#                            {% for value in attr_value %}#}
                    {#                                {% for param in value %}#}
                    {#                                    {% if param.typical_pr_attr_id.id == attr.id %}#}
                    {#                                        <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">#}
                    {#                                            <label class="custom-control-input" for="">{{ param }}</label>#}
                    {#                                            <input type="checkbox" class="custom-control-input" id="">#}
                    {#                                        </div>#}
                    {#                                    {% endif %}#}
                    {#                                {% endfor %}#}
                    {#                            {%  endfor %}#}
                    {#                        </div>#}
                    {#                    {% endfor %}#}
                    <button type="submit" class="btn btn-block btn-primary font-weight-bold my-2 py-2">Search</button>
                </form>
                {#                <!-- Color Start -->#}
                {#                    <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">LENS</span></h5>#}
                {#                    <div class="bg-light p-4 mb-30">#}
                {#                        <form>#}
                {#                            {% for gr in param_names.LENS %}#}
                {#                                <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">#}
                {#                                    <input type="checkbox" class="custom-control-input" id="">#}
                {#                                    <label class="custom-control-label" for="">{{ gr.0 }}</label>#}
                {#                                    <span class="badge border font-weight-normal">150</span>#}
                {#                                </div>#}
                {#                            {%  endfor %}#}
                {#                        </form>#}
                {#                    </div>#}
                {#                <!-- Color End -->#}
            </div>
            <!-- Shop Sidebar End -->


            <!-- Shop Product Start -->
            <div class="col-lg-9 col-md-8">
                <div class="row pb-3">
                    <div class="col-12 pb-1">
                        <div class="d-flex align-items-center justify-content-between mb-4">
                            <div>
                                <button class="btn btn-sm btn-light"><i class="fa fa-th-large"></i></button>
                                <button class="btn btn-sm btn-light ml-2"><i class="fa fa-bars"></i></button>
                            </div>
                            <div class="ml-2">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-sm btn-light dropdown-toggle"
                                            data-toggle="dropdown">Sorting
                                    </button>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        <a class="dropdown-item" href="#">Latest</a>
                                        <a class="dropdown-item" href="#">Popularity</a>
                                        <a class="dropdown-item" href="#">Best Rating</a>
                                    </div>
                                </div>
                                <div class="btn-group ml-2">
                                    <button type="button" class="btn btn-sm btn-light dropdown-toggle"
                                            data-toggle="dropdown">Showing
                                    </button>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        <a class="dropdown-item" href="#">10</a>
                                        <a class="dropdown-item" href="#">20</a>
                                        <a class="dropdown-item" href="#">30</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    {% for product in object_list %}
                        <div class="col-lg-4 col-md-6 col-sm-6 pb-1">
                            <div class="product-item bg-light mb-4">
                                <div class="product-img position-relative overflow-hidden">
                                    <img class="img-fluid w-100" src="{{ product.image.url }}" alt="">
                                    <div class="product-action">
                                        <a class="btn btn-outline-dark btn-square"
                                           href="{% url 'shoping_cart:add_to_cart' product.id %}"><i
                                                class="fa fa-shopping-cart"></i></a>
                                        <a class="btn btn-outline-dark btn-square"
                                           href="{% url 'shoping_cart:add_to_likes' product.id %}"><i
                                                class="far fa-heart"></i></a>
                                        {#                                    <a class="btn btn-outline-dark btn-square" href=""><i class="fa fa-sync-alt"></i></a>#}
                                        <a class="btn btn-outline-dark btn-square"
                                           href="{% url 'test:product_detail' product.id %}"><i
                                                class="fa fa-search"></i></a>
                                    </div>
                                </div>
                                <div class="text-center py-4">
                                    <a class="h6 text-decoration-none text-truncate"
                                       href="{% url 'test:product_detail' pk=product.id %}">{{ product.name }}</a>
                                    <div class="d-flex align-items-center justify-content-center mt-2">
                                        <h5>{{ product.price }}</h5>
                                        <h6 class="text-muted ml-2">
                                            <del>{{ product.price }}</del>
                                        </h6>
                                    </div>
                                    <div class="d-flex align-items-center justify-content-center mb-1">
                                        <small class="fa fa-star text-primary mr-1"></small>
                                        <small class="fa fa-star text-primary mr-1"></small>
                                        <small class="fa fa-star text-primary mr-1"></small>
                                        <small class="fa fa-star text-primary mr-1"></small>
                                        <small class="fa fa-star text-primary mr-1"></small>
                                        <small>(99)</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}



                    <div class="col-12">
                        <nav>
                            <ul class="pagination justify-content-center">
                                <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                                <li class="page-item active"><a class="page-link" href="#">1</a></li>
                                <li class="page-item"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item"><a class="page-link" href="#">Next</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
            <!-- Shop Product End -->
        </div>
    </div>
    <!-- Shop End -->
{% endblock %}

multi_store/templates/multi_store/shop_categories.html
{% extends 'multi_store/base.html' %}
{% load static %}

{% block content %}
        <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="{% url 'test:index' %}">Home</a>
                    <span class="breadcrumb-item active">Shop Categories</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->
    <!-- Categories Start -->
    <div class="container-fluid pt-5">
        <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">Categories</span>
        </h2>
        <div class="row px-xl-5 pb-3">
            {% for category in object_list %}
                <div class="col-lg-3 col-md-4 col-sm-6 pb-1">
                    <a class="text-decoration-none" href="{% url 'test:shop_groups' category_id=category.id %}">
                        <div class="cat-item img-zoom d-flex align-items-center mb-4">
                            <div class="overflow-hidden" style="width: 100px; height: 100px;">
                                <img class="img-fluid" src="{% static 'img/cat-2.jpg' %}" alt="">
                            </div>
                            <div class="flex-fill pl-3">
                                <h6>{{ category.name }}</h6>
                                <small class="text-body">{{ category.description }}</small>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
    <!-- Categories End -->
{% endblock %}

multi_store/templates/multi_store/shop_groups.html
{% extends 'multi_store/base.html' %}
{% load static %}

{% block content %}
        <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="{% url 'test:index' %}">Home</a>
                    <a class="breadcrumb-item text-dark" href="{% url 'test:shop_category' %}">Shop Categories</a>
                    <span class="breadcrumb-item active">Shop Groups</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->
    <!-- Categories Start -->
    <div class="container-fluid pt-5">
        <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">Groups</span>
        </h2>
        <div class="row px-xl-5 pb-3">
            {% for group in object_list %}
                <div class="col-lg-3 col-md-4 col-sm-6 pb-1">
                    <a class="text-decoration-none" href="{% url 'test:shop_products' group_id=group.id%}">
                        <div class="cat-item img-zoom d-flex align-items-center mb-4">
                            <div class="overflow-hidden" style="width: 100px; height: 100px;">
                                <img class="img-fluid" src="{% static 'img/cat-2.jpg' %}" alt="">
                            </div>
                            <div class="flex-fill pl-3">
                                <h6>{{ group.name }}</h6>
                                <small class="text-body">{{ group.description }}</small>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
    <!-- Categories End -->
{% endblock %}